config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
  	resources :exercises
  end
  get "/pages/:page" => "pages#show"
  root "pages#show", page: "home"
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def create
		@workout = Workout.find(params[:workout_id])
		@exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))
	
	redirect_to workout_path(@workout)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_action :find_workout, only: [:show, :edit, :update, :destroy]
	def index
		@workouts = Workout.all.order("created_at DESC")
	end

	def show
	end

	def new
		@workout = Workout.new
	end

	def create
		@workout = Workout.new(workout_params)
		if @workout.save
			redirect_to @workout
		else
			render 'new'
		end
	end

	def print_strftime_formats(a,cur_date)
   a.each do |format|
   b = "%#{format}"
   output = cur_date.strftime(b)
   puts "t.strftime('#{b}'), => #{output}"
   end
	end

def edit
	end

	def update
		if @workout.update(workout_params)
			redirect_to @workout 
		else
			render 'edit'
		end
	end

	def destroy
		@workout.destroy
		redirect_to root_path
	end 

private

	def workout_params
		params.require(:workout).permit(:date, :workout, :mood, :length)
	end

	def find_workout
		@workout = Workout.find(params[:id])
	end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/storys_helper.rb
module StorysHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.haml
%p= exercise.name
%p= exercise.sets
%p= exercise.reps

app/views/exercises/_form.html.haml
= simple_form_for([@workout, @workout.exercises.build]) do |f|
	= f.input :name, input_html: { class: "form-control"}
	= f.input :sets, input_html: { class: "form-control"}
	= f.input :reps, input_html: { class: "form-control"}
	%br/
	= f.button :submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Workout Log Application
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-header
				= link_to "My StayFit", workouts_path, class: "navbar-brand"
			.nav.navbar-nav.navbar-right
				=link_to "New Workout", new_workout_path, class: "navbar navbar-link"
	.container
		= yield

app/views/pages/home.html.erb
<div id="bootstrap-overrides">
	<h1>StayFit</h1>
</div>

app/views/workouts/_form.html.erb
  <div class="jumbotron">
    <%= simple_form_for(@workout, html: { class: "form-horizontal" }) do |f| %>
      <h4>
      <%= f.input :date, label: "Date" %>
      <%= f.input :workout, label: "What area did you workout?", input_html: { class: "form-control" } %>
      <%= f.input :mood, label: "How were you feeling?", input_html: { class: "form-control" } %>
      <%= f.input :length, label: "How long was the workout?", input_html: { class: "form-control" } %>
      <br/>
      </h4>
     <%= f.submit :class => "btn btn-default btn-lg" %>
    <% end %>
  </div>

app/views/workouts/edit.html.haml
%h1 Edit Workout

= render 'form'

= link_to "Cancel", root_path

app/views/workouts/index.html.erb
<div id="new-workout">
  <% @workouts.each do |workout| %>
    <h1>
      <%= link_to workout.date.strftime("%A %B %d"), workout %>
    </h1>
    <h3>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= workout.workout %>
    </h3>
  <% end %>
</div>

app/views/workouts/new.html.erb
	
	<div id="new-workout">	
		<h1>New Workout</h1>
		<%= render 'form' %>
		<%= link_to "Cancel", root_path %>
	</div>

app/views/workouts/show.html.erb
<div class="jumbotron">
  <div id="workout">
    <p>
      <strong>Date:</strong> <%= @workout.date %>
    </p>
    <p>
      <strong>Workout:</strong> <%= @workout.workout %>
    </p>
    <p>
     <strong>Mood:</strong> <%= @workout.mood %>
    </p>
    <p>
      <strong>Length:</strong> <%= @workout.length %>
    </p>
  </div>
  <div id="exercises">
    <h2>Exercises</h2>
    <%= render@workout.exercises %>
    <%= render "exercises/form" %>
  </div>
  <%= link_to "Back", root_path %>
  |
  <%= link_to "Edit", edit_workout_path(@workout) %>
  |
  <%= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" } %>
</div>